/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.group1.shared;



import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Map;


/*
player information model
it is the data used for server to send information to client
 */
@javax.persistence.Entity
public class PlayerInfo implements Serializable {
    /*  this player's id */
    @javax.persistence.Id
    private int playerId;

    /* the map of current game */
    private AbstractMap map;
    /* player status indicates what action the client should make */
    private String status;
    /* whether it need wait other players */
    private Boolean needWait;
    /* whether the player is currently online */
    private Boolean online;
    /* the room it is in */
    private int currRoomId;
    /* the account for the player */
    private String account;
    /* the password for the player */
    private String password;
    /* the message for login/register */
    private String loginMsg;
    /* the available rooms for the player */
    @javax.persistence.ElementCollection
    private Map<Integer, String> AvailableRooms;




    public PlayerInfo() {
        playerId = -1;
    }

    /**
     * Constructs a playerinfo object
     * @param playerId is the player's id, currently it is the number of user connected to the server
     */
    public PlayerInfo(int playerId) {
        this.playerId = playerId;
        this.status = "";
        this.needWait = true;
        this.currRoomId = -1;
        this.online = false;
    }

    public String getStatus(){
        return status;
    }

    public void setStatus(String status){
        this.status = status;
    }

    public int getPlayerId() {
        return playerId;
    }

    public void setMap(AbstractMap map){
        this.map = map;
    }

    public AbstractMap getMap(){ return map; }

    public void setNeedWait(Boolean needWait) {
        this.needWait = needWait;
    }

    public Boolean getNeedWait() {
        return needWait;
    }

    public void setCurrRoomId(int currRoomId) {
        this.currRoomId = currRoomId;
    }

    public int getCurrRoomId() {
        return currRoomId;
    }

    public String getAccount() {
        return account;
    }

    public String getPassword() {
        return password;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getLoginMsg() {
        return loginMsg;
    }

    public void setLoginMsg(String loginMsg) {
        this.loginMsg = loginMsg;
    }

    public void setAvailableRooms(Map<Integer, String> availableRooms) {
        AvailableRooms = availableRooms;
    }

    public Map<Integer, String> getAvailableRooms() {
        return AvailableRooms;
    }

    public Boolean getOnline() {
        return online;
    }

    public void setOnline(Boolean online) {
        this.online = online;
    }
}
