/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.group1.server;

import edu.duke.group1.shared.*;
import org.checkerframework.checker.units.qual.Time;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.concurrent.TimeUnit;

public class AppTest {


    //@Test
    public void appTestConnection()  throws IOException {
        App app = new App();
        //app.acceptConnection();
    }

   // @Test
    public void test_getPlayerInfoSize() throws IOException {
        App app = new App();
        assert(app.getPlayerInfoSize() == 0);

        app.addPlayerInfo(1);
        assert(app.getPlayerInfoSize() == 1);
    }

    //@Test
    public void test_getPLayerInfo() throws IOException {
        App app = new App();

        app.addPlayerInfo(0);
        app.addPlayerInfo(1);
        app.addPlayerInfo(2);
        app.addPlayerInfo(3);
        app.addPlayerInfo(4);

        assert(app.getPlayerInfo(2) != null);
        assert(app.getPlayerInfo(0).getStatus().equals("choosePlayerNum"));

    }

   // @Test
    public void test_Room() throws IOException {
        App app = new App();

        app.addPlayerInfo(0);
        app.addPlayerInfo(1);
        app.addPlayerInfo(2);
        app.addPlayerInfo(3);
        app.addPlayerInfo(4);

        app.createRoom(0, 5);
        Room room = app.getRoomById(0);
        app.joinRoom(1, room.getRoomId());
        app.joinRoom(2, room.getRoomId());
        app.joinRoom(3, room.getRoomId());
        app.joinRoom(4, room.getRoomId());


        Room room1 = app.getRoomById(566);
        assert(room1 == null);
    }

    //@Test
    public void test_processAction() throws IOException, InterruptedException {
        App app = new App();
        app.addPlayerInfo(0);
        Action action = new ChoosePlayerNumAction(5);
        app.processAction(action, 0);

        assert(app.getPlayerInfo(0).getStatus().equals("doPlacement"));

        Action action2 = new EmptyAction();
//        app.createRoom(0,5);
        app.processAction(action2, 0);
//        Action action3 = new Action() {
//            @Override
//            public void doAction(AbstractMap map) {
//                System.out.println("test");
//            }
//        };
//
//        app.processAction(action3, 0);
    }


}

