/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.group1.client;

import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.ListView;
import javafx.scene.control.TextField;
import javafx.scene.layout.*;
import javafx.stage.Stage;


import java.io.*;
import java.net.URL;

/*
client app entrypoint
 */
public class App extends Application{
    public static Player player;
    public static Stage ps;

    @Override
    public void start(Stage primaryStage) throws Exception {
        ps = primaryStage;

        Scene scene = LoginController.show();
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    /**
     * Start a game client
     * ipaddr and port can be changed to the server ip
     */
    @FXML
    public static void main(String[] args) throws IOException, ClassNotFoundException {
        String ipAddr = "127.0.0.1";
        int port = 54321;

        if(args.length == 0){
             player = new Player(ipAddr, port);
        }else{
            // this is used for test, if you want to run it,
            // delete it and un-comment the above code
             player = new Player(ipAddr, Integer.parseInt(args[0]));
        }

        Application.launch();
    }


}
